#+title: Proceso de pruebas para los proyectos
#+setupfile: setup.org

* QA en el proyecto

Es *necesario y obligatorio* hacer un proceso de QA en el proyecto.

#+REVEAL: split

Tenéis libertad para plantearlo como queráis, pero parte de la entrega
final tendrá que incluir un estudio con gente externa

#+REVEAL: split

Para hacer pruebas válidas, hay que hacer que gente representativa de
nuestro /target/ juegue al juego

#+REVEAL: split

Y, también, estudiar lo que /hacen/ y lo que /dicen/

#+REVEAL: split

Por tanto, hay dos partes principales que resolver:

- Quién va a jugar y probar mi juego (no pueden ser los miembros del
  equipo)
- Cómo se va a observar el proceso

* Quiénes

#+REVEAL: split

Es importante que se elija un grupo de personas que represente nuestro
objetivo

(No tiene sentido probar un juego infantil con adultos)

#+REVEAL: split

Es difícil conseguir gente de forma general, y hay que intentar no
cansar a los sujetos

#+REVEAL: split

Las pruebas con externos no reemplazan a vuestras pruebas de calidad,
son algo adicional

* Cuándo y cuánto

#+REVEAL: split

Hay que decidir cuándo hacer baterías de /testing/

#+REVEAL: split

No tiene sentido hacerlas muy pronto porque no hay prototipo

No tiene sentido hacerlas muy tarde porque no hay tiempo para usar los
datos

#+REVEAL: split

No se pueden hacer pruebas muy costosas todas las semanas

No tiene sentido hacer pruebas cada 2 meses

#+REVEAL: split

Aproximadamente, tendréis que hacer una batería de pruebas + informe una
vez por hito, pero no viene mal hacer más

* Qué preguntar

#+REVEAL: split

Si preguntáis...

#+begin_quote
¿Te ha gustado el juego?

#+end_quote

#+REVEAL: split

... ¿vais a obtener información útil?

#+REVEAL: split

- ¿Te ha parecido muy rápido el movimiento?
- Evalúa, de 1 a 5, la dificultad del nivel 1
- ¿Qué cambiarías?
- ¿Cuáles son las cosas que más te han gustado?
- ¿Y las que menos?

** No preguntéis todo

Las opiniones son útiles, pero saber lo que hacen los jugadores, mucho
más:

#+REVEAL: split

- ¿Cuánto tiempo se tarda en pasar la demo?
- ¿Cuánto tardan en aprender?
- ¿Qué mecánicas usan más?
- ¿Se leen todo el texto?
- ¿Qué partes del nivel no se exploran? \(\rightarrow\) Buen sitio para preguntar por qué


** Formato

Está bien hablar, pero tenéis que /almacenar información/

#+REVEAL: split

Preguntad con un Google Sheet (por ejemplo), almacenad todo en una hoja
de cálculo, tomad notas...

* Informe

#+REVEAL: split

En la documentación general del proyecto tenéis que tener un informe de
pruebas:

- Cuándo se han hecho, con cuánta gente cada vez, qué se les ha
  preguntado, y qué ha salido
- Una conclusión general de las pruebas (resumiendo todo hasta la fecha)

#+REVEAL: split

Pero, lo más importante...

** Uso del informe

- ¿Cómo se ha aplicado la información de QA al proyecto?
- ¿Qué cambios se han hecho?
- ¿Qué problemas/limitaciones se han descubierto?

# Local variables:
# after-save-hook: org-re-reveal-export-to-html
# end:

